services:
  - type: web
    name: bserp-api
    runtime: docker
    repo: https://github.com/Ousmane-ndao/BSERP.git
    branch: master
    dockerfile: ./backend/Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: bserp-db
          property: connectionString
    healthCheckPath: /health
    healthCheckInterval: 30
    healthCheckTimeout: 10
    healthCheckStartupFailureThreshold: 40
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 70
      targetCPUPercent: 70

databases:
  - name: bserp-db
    ipAddress: private
    engine: postgres
    version: latest
    plan: standard
    postgresMajorVersion: "16"
